name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome messege
          run: echo "my action"
        - name: list files
          run: ls
        - name: cat file
          run: cat README.md