name: generat ascii

on: 
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: install cowsay
      run: sudo apt-get install cowsay -y
    - name: excute cowsay
      run: cowsay -f dragon "run for covrt,,,arrr" >> dragon.txt
    - name: read file
      run: cat dragon.txt