name: generate ascii-artwork

on: 
  push 

jobs: 
  build_job:
    runs-on: ubuntu-latest 
    steps:
    - name: install cowsay program 
      run: sudo apt-get install cowsay -y 
    
    - name: excute cowsay program 
      run: cowsay -f dragon "run for cover human!" >> dragon.txt 

    - name: sleep for 30 second 
      run: sleep 30
      
    - name: upload the file 
      uses: actions/upload-artifact@v3
      with: 
        name: my-artifact
        path: dragon.txt

  test_job: 
    runs-on: ubuntu-latest 
    needs: build_job
    steps: 
    - name: download the file 
      uses: actions/download-artifact@v3
      with: 
        name: my-artifact

    - name: test the file 
      run: grep -i "dragon" dragon.txt

  deploy_job:
    runs-on: ubuntu-latest 
    needs: test_job
    steps:
    - name: download the file 
      uses: actions/download-artifact@v3
      with: 
        name: my-artifact
        
    - name: show the file 
      run: cat dragon.txt

    - name: deploy 
      run: echo deploying .... 
